
const APP_DOMAIN = process.env.NEXT_PUBLIC_APP_DOMAIN
const SUPABASE_POSTGRES_URL= process.env.NEXT_PUBLIC_SUPABASE_POSTGRES_URL
const NEXT_PUBLIC_APP_URL = process.env.NEXT_PUBLIC_APP_URL


export {
  APP_DOMAIN,
  SUPABASE_POSTGRES_URL,
  NEXT_PUBLIC_APP_URL
}